### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by s6juncheng** [kundajelab/tfmodisco#1]
https://github.com/kundajelab/tfmodisco/blob/81f2aa49bf4009f7e2bf2fabe0c61394f6a464c8/modisco/util.py#L468

I got a syntax error with python 3.5.
```
    except Exception, _:
                    ^
SyntaxError: invalid syntax
```
same for https://github.com/kundajelab/tfmodisco/blob/81f2aa49bf4009f7e2bf2fabe0c61394f6a464c8/modisco/util.py#L502

need to change to 
```
except (Exception, _):
except (KeyboardInterrupt, OSError):
```

thanks,
Jun

**Comment by AvantiShri** [comment]
Hi @s6juncheng, I just pushed a new tagged version that looks like it's working with python 3. Here's the [updated example notebook](https://github.com/kundajelab/tfmodisco/blob/v0.2-alpha/examples/simulated_tf_binding/TF%20MoDISco%20TAL%20GATA.ipynb). Thanks to @Avsecz for getting this started.
