### ISSUE TITLE
Using without tasks

### ISSUE THREAD

**Issue by TommyJW** [kundajelab/tfmodisco#31]
I'm an undergrad working with sequence analysis. Currently, I'm attempting to implement TF MoDISco to work with my dataset. So far, I've generated the importance scores via DeepLIFT, and saved to an h5 file similar to "Generate Importance Scores.ipynb" now I'm working on importing like "TF MoDISco TAL GATA.ipynb" does.

However, when I try to call 'modisco.tfmodisco_workflow.workflow.TfModiscoWorkflow' it requires a list of tasks. This I do not have. 

With my data I'm exploring a sequence of binding lncRNA and cannot assume that any sequence contains motifs that are similar to another sequence. If I understand the video correctly, the 3 tasks presented do have such a relationship. 

Will TF MoDISco fit such a need (isolated 'task-less') motif discovery? Am I using the correct methods?

export like Generate Importance Scores.ipynb
`#save the scores and hypotheticals

```
if (os.path.isfile("scores.h5")):
    !rm scores.h5
f = h5py.File("scores.h5")
g = f.create_group("contrib_scores")
g.create_dataset("task", data=scores)
g = f.create_group("hyp_contrib_scores")
g.create_dataset("task", data=hyp_contrib_scores)
f.close()
```

import like TF MoDISco TAL GATA.ipynb
```
f = h5py.File("scores.h5","r")
scores = [np.array(x) for x in f['contrib_scores']["task"][:]]
hyp_scores = [np.array(x) for x in f['hyp_contrib_scores']["task"][:]]

tfmodisco_results = modisco.tfmodisco_workflow.workflow.TfModiscoWorkflow(
                    #Slight modifications from the default settings
                    sliding_window_size=21,
                    flank_size=10,
                    target_seqlet_fdr=0.01,
                    seqlets_to_patterns_factory=
                     modisco.tfmodisco_workflow.seqlets_to_patterns.TfModiscoSeqletsToPatternsFactory(
                        trim_to_window_size=30,
                        initial_flank_to_add=10,
                        kmer_len=7, num_gaps=3,
                        num_mismatches=2,
                        final_min_cluster_size=60)
                )(
                task_names=["task"],
                contrib_scores=scores,
                hypothetical_contribs=hyp_scores,
                one_hot=pos_train_onehot_data)

```

**Comment by AvantiShri** [comment]
Hi Tommy,

Thanks for making a github issue. If you have importance scores, it's effectively like having one task called, in your case, "task". Can you try the following:

```
f = h5py.File("scores.h5","r")
scores = [np.array(x) for x in f['contrib_scores']["task"][:]]
hyp_scores = [np.array(x) for x in f['hyp_contrib_scores']["task"][:]]

tfmodisco_results = modisco.tfmodisco_workflow.workflow.TfModiscoWorkflow(
#Slight modifications from the default settings
sliding_window_size=21,
flank_size=10,
target_seqlet_fdr=0.01,
seqlets_to_patterns_factory=
modisco.tfmodisco_workflow.seqlets_to_patterns.TfModiscoSeqletsToPatternsFactory(
trim_to_window_size=30,
initial_flank_to_add=10,
kmer_len=7, num_gaps=3,
num_mismatches=2,
final_min_cluster_size=60)
)(
task_names=["task"],
contrib_scores={"task": scores},
hypothetical_contribs={"task": hyp_scores},
one_hot=pos_train_onehot_data)
```
Does that make sense? You may end up with up to two metaclusters: one for seqlets that have positive scores for the task and the other for seqlets that have negative scores for the task (you may also just end up with one metacluster if there aren't enough negative seqlets).

**Comment by TommyJW** [comment]
Yes that made sense, and moved through the first issue. Now I get:
```---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-19-934e7f9753bb> in <module>
     15                 contrib_scores={"task": scores},
     16                 hypothetical_contribs={"task": hyp_scores},
---> 17                 one_hot=pos_train_onehot_data)

~/.local/share/virtualenvs/SeniorProject-AFH1tCxG/lib/python3.6/site-packages/modisco/tfmodisco_workflow/workflow.py in __call__(self, task_names, contrib_scores, hypothetical_contribs, one_hot)
    191                         contrib_scores=contrib_scores,
    192                         hypothetical_contribs=hypothetical_contribs,
--> 193                         one_hot=one_hot)
    194 
    195         per_position_contrib_scores = OrderedDict([

~/.local/share/virtualenvs/SeniorProject-AFH1tCxG/lib/python3.6/site-packages/modisco/tfmodisco_workflow/workflow.py in prep_track_set(task_names, contrib_scores, hypothetical_contribs, one_hot)
    130     track_set = core.TrackSet(
    131                     data_tracks=contrib_scores_tracks
--> 132                     +hypothetical_contribs_tracks+[onehot_track])
    133     return track_set
    134 

~/.local/share/virtualenvs/SeniorProject-AFH1tCxG/lib/python3.6/site-packages/modisco/core.py in __init__(self, data_tracks, attribute_providers)
     92         self.attribute_name_to_attribute_provider = OrderedDict()
     93         for data_track in data_tracks:
---> 94             self.add_track(data_track)
     95         for attribute_provider in attribute_providers:
     96             self.attribute_name_to_attribute_provider[attribute_provider.name]\

~/.local/share/virtualenvs/SeniorProject-AFH1tCxG/lib/python3.6/site-packages/modisco/core.py in add_track(self, data_track)
    109             assert len(data_track)==self.num_items,\
    110                     ("first track had "+str(self.num_items)+" but "
--> 111                      "data track has "+str(len(data_track))+" items")
    112         self.track_name_to_data_track[data_track.name] = data_track
    113         return self

AssertionError: first track had 67 but data track has 416 items```

My data is a 3D one hot: seq, SeqenceElements, GATC so (416, 2551, 4). What is a Track, and what is it expecting to be size 67?

To your question about motifs. I think I misunderstood the example. I'm working with enough data that we will likely find motifs (especially for the larger ones). However, the video seemed to indicate that the program is comparing CTCF, ZNF143, and SIX5 to determine motifs common between them. I apologize for my ignorance, I'm a CS major and just started working with molecular biology recently. Much of the terminology is still very new to me.

**Comment by AvantiShri** [comment]
Hi Tommy,

A DataTrack is a wrapper around a numpy array containing a type of data. The one-hot encoded sequence, hypothetical scores and actual scores are all different data tracks. The error presumably thrown because your data tracks have a different number of entries in them. Can you print out the values of scores.shape, hyp_scores.shape and pos_train_onehot_data.shape? All three should be (416, 2551, 4); the error suggests that one of them is of length 67 in the first dimension.

One more thing: the ordering of your channels one-hot encoding is not what I was expecting. Generally, I'm used to the one-hot encoding channels being in alphabetical order (ACGT). I'm surprised to see GATC - is there a paper that uses this? Regardless, my visualization code assumes an ordering of ACGT, so you may want to rearrange the row ordering for ease of visualization.

Ah, yes, metaclusters group the seqlets according to their activity pattern across different tasks (seqlets are short subsequences with high importance). However, if you have just one task, then your potential metaclusters are just "positive for the task" and "negative for the task".

Let me know if you have any other questions!

**Comment by TommyJW** [comment]
Thanks, I updated my response, and found the sizing issue, it stemmed from export/import of different data sets between my two .py 's. I think this particular issue is good to close. Thanks again.
