### ISSUE TITLE
viz_sequence plot

### ISSUE THREAD

**Issue by MMostavi** [kundajelab/tfmodisco#41]
Hi Avanti,

I have noticed that when we plot the output of sequences, the location of nucleotide starts at index zero (which it needs to be one), and the nucleotide is between two locations(rather than being in the middle).

Also, how can we replace the letter 'T' with 'U' when we want to plot for RNA sequences?

![sample_seqout](https://user-images.githubusercontent.com/22861849/58765825-8658a880-853c-11e9-9a65-a17871c610a5.png)

ps: I tried few things but couldn't fix all together correctly. Also great works both deeplift and modisco.

**Comment by AvantiShri** [comment]
I just added this functionality to the vizsequence library, which can be installed with `!pip install vizsequence`. The code would be:
```
from vizsequence.viz_sequence import rna_plot_weights
rna_plot_weights(...same arguments you previously provided to plot_weights...)
```
This is what it looks like:

![download](https://user-images.githubusercontent.com/2302598/59024642-33664600-8807-11e9-88fb-b76f52c67eab.png)

I'll admit the "U" isn't as pretty as it could be, but this seems to be a limitation of creating the letters using native matplotlib polygons. The concise library by @Avsecz also has functionality for generating such logos (https://github.com/gagneurlab/concise/blob/d15262eb1e590008bc96ba31e93bfbdbfa1a9fd4/concise/utils/plot.py#L196), but it relies on GEOS, which may not be installed on your system.

Here's an example colab notebook: https://github.com/kundajelab/vizsequence/blob/master/examples/ExampleNotebook.ipynb

Does this satisfy your needs?

**Comment by MMostavi** [comment]
Yes thanks. It works perfectly. 

"U" is not very well drawn but it's okay. 

Sorry I was in a trip and couldn't check the code earlier.
