### ISSUE TITLE
libary import leidenalg and tqdm is missing in the dependencies

### ISSUE THREAD

**Issue by visze** [kundajelab/tfmodisco#58]
after running the newest version I get the error:

```
  File "tfmodisco/modisco/cluster/core.py", line 7, in <module>
    import leidenalg
ModuleNotFoundError: No module named 'leidenalg'
```
Same with tqdm

after installling leidenalg and tqdm (here I used 
`conda install -c conda-forge leidenalg tqdm`) the error is gone:

I think you should add them to the dependencies in your setup file

**Comment by AvantiShri** [comment]
Thank you for catching this! Pushed an update in v0.5.6.2.
